<a href="https://colab.research.google.com/github/LongNguyen0612/D13CNPM4_NguyenDacNhatLong/blob/main/Hoc_may_2_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
#from IPython.display import display
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import learning_curve
#from sklearn.externals import joblib
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [ ]:
df = pd.read_excel('sentimentvn.xlsx')
df

label                                               text
0         1  Thiết kế đẹp nhưng không hiểu sao lại để đám c...
1         1  Công nhận là không còn điện thoại nào rẻ hơn đ...
2         1  Hiện tại dùng Prime 805 cày game mobile , để q...
3         1  Em nghĩ bác nên dùng qua mới biết được . Tuy p...
4         1                         Pin khá hơn tí thì tốt nhỉ
...     ...                                                ...
4004      0  định quay về với sony nhưng thôi thiết kế này ...
4005      0  Đã dùng sony thấy giao diện nặng nề quá. không...
4006      0  Cái này không dành cho người bình dân và giàu,...
4007      0  Đắt quá, với giá này còn nhiều sự lựa chọn khá...
4008      0  Mỗi tội cái logo samsung nhìn tức mắt vãi, đặt...

[4009 rows x 2 columns]

In [ ]:
stopword=[]
stopword.append('.')
stopword.append(',')
stopword.append(';')
#stopword.append('ứng')

print(stopword)
def clean_tweets(df):
    df['text']=df['text'].str.lower()
    return df

['.', ',', ';']


In [ ]:
X=df['text'].to_list()

print('X=',X)

y=df['label'].to_list()
print('y=',y)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=10)

X= ['Thiết kế đẹp nhưng không hiểu sao lại để đám chữ " 8.0 autofocus " ở camera chi không biết , nhìn hơi quê , nếu không có thì sẽ đẹp hơn . Giờ mấy máy cao cấp đâu ai để mấy thông số đó lên máy đâu .', 'Công nhận là không còn điện thoại nào rẻ hơn điên thoại này , V843 của Viettel củng phải gọi là cụ', 'Hiện tại dùng Prime 805 cày game mobile , để qua đêm cắm sạc play game không bị văng .', 'Em nghĩ bác nên dùng qua mới biết được . Tuy pin 2k nhưng dùng được wifi 4h liên tục , về khoản pin này thì em chắc nhiều con của các hãng danh tiếng chưa chắc đã bằng', 'Pin khá hơn tí thì tốt nhỉ', 'Gì cũng ngon trừ pin và . . . brand . Pin 2500 thì ngon hơn', 'Đã trên tay em này , cầm không được sướng tay cho lắm , nhưng được cái đẹp , camera chấp nhận được . Màu đen khá sâu , máy này chỉ dành cho nam', 'Em nó độ hoàn thiện cũng khá good đấy .', 'Ngon nhỉ " . . . . . . . . .', 'theo bảng cấu hình thì có lẽ xử lý đồ hoạ rất tốt .', 'đẹp đấy chứ , nhìn nam tính , không có hình bản màu đen nhỉ',

In [ ]:
Vectorizer = CountVectorizer(analyzer = u'word',ngram_range=(1, 1),stop_words=set(stopword))
TfIdf=Vectorizer.fit(X_train)
X_train=TfIdf.transform(X_train)
X_test=TfIdf.transform(X_test)
print('Ma tran X_train=',X_train.todense())
print('X_train.shape=',X_train.shape)

Ma tran X_train= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
X_train.shape= (3207, 4016)


In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1500)

print('X_train.todense=',X_train.todense())
X_trainPCA = pca.fit_transform(X_train.todense())

X_testPCA = pca.transform(X_test.todense())
print('X_train_pca=',X_trainPCA)

X_train.todense= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
X_train_pca= [[-0.99584904  0.05731993  0.02127657 ... -0.02871085  0.02737515
   0.01505363]
 [-0.39677219 -0.18031523 -0.15307651 ... -0.01642079  0.03326572
  -0.01238488]
 [-0.25934794 -0.02258687 -0.1041892  ... -0.02291208 -0.01037347
  -0.00507925]
 ...
 [-0.46755409  0.15479025  0.27521952 ... -0.01343354  0.03481636
  -0.00777168]
 [-0.18553485 -1.09043704 -0.03206104 ... -0.01003175 -0.00800758
  -0.00792538]
 [-1.13927201  0.01227451  0.16065569 ... -0.00569231  0.00560812
   0.00543157]]


In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X_trainLDA = lda.fit_transform(X_train.todense(), y_train)
X_testLDA = lda.transform(X_test.todense())

In [ ]:
# SỬ DỤNG SVM
print('SVM & PCA')
model =svm.LinearSVC(C=0.1)
model.fit(X_trainPCA,y_train)

SVM & PCA


LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
# evaluation (Bước đánh giá tính hiệu quả của mô hình) 
y_pred=model.predict(X_testPCA)

print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: \n',confusion_matrix(y_test, y_pred))

Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: 
               precision    recall  f1-score   support

           0     0.7584    0.7260    0.7418       281
           1     0.8555    0.8752    0.8653       521

    accuracy                         0.8229       802
   macro avg     0.8069    0.8006    0.8035       802
weighted avg     0.8215    0.8229    0.8220       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: 
 [[204  77]
 [ 65 456]]


In [ ]:
print('SVM & LDA')
model =svm.LinearSVC(C=0.1)
model.fit(X_trainLDA, y_train)

SVM & LDA


LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
# evaluation (Bước đánh giá tính hiệu quả của mô hình) 
y_pred=model.predict(X_testLDA)

print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: \n',confusion_matrix(y_test, y_pred))

Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: 
               precision    recall  f1-score   support

           0     0.5153    0.6584    0.5781       281
           1     0.7833    0.6660    0.7199       521

    accuracy                         0.6633       802
   macro avg     0.6493    0.6622    0.6490       802
weighted avg     0.6894    0.6633    0.6702       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: 
 [[185  96]
 [174 347]]


In [ ]:
print("SVM ko sử dụng PCA hay LDA")
model =svm.LinearSVC(C=0.1)
model.fit(X_train, y_train)

SVM ko sử dụng PCA hay LDA


LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
y_pred=model.predict(X_test)

print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: \n',confusion_matrix(y_test, y_pred))

Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: 
               precision    recall  f1-score   support

           0     0.7724    0.7367    0.7541       281
           1     0.8614    0.8829    0.8720       521

    accuracy                         0.8317       802
   macro avg     0.8169    0.8098    0.8131       802
weighted avg     0.8302    0.8317    0.8307       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: 
 [[207  74]
 [ 61 460]]


In [ ]:
# Sử dụng Logistic
# Ko PCA hay LDA
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)

classifier.fit(X_train, y_train)

#predicting results

y_pred = classifier.predict(X_test)
print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: \n',confusion_matrix(y_test, y_pred))

Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: 
               precision    recall  f1-score   support

           0     0.7647    0.7402    0.7523       281
           1     0.8623    0.8772    0.8696       521

    accuracy                         0.8292       802
   macro avg     0.8135    0.8087    0.8110       802
weighted avg     0.8281    0.8292    0.8285       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: 
 [[208  73]
 [ 64 457]]


In [ ]:
# PCA
classifier = LogisticRegression(random_state = 0)

classifier.fit(X_trainPCA, y_train)

#predicting results

y_pred = classifier.predict(X_testPCA)
print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: \n',confusion_matrix(y_test, y_pred))

Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: 
               precision    recall  f1-score   support

           0     0.7621    0.7295    0.7455       281
           1     0.8574    0.8772    0.8672       521

    accuracy                         0.8254       802
   macro avg     0.8097    0.8033    0.8063       802
weighted avg     0.8240    0.8254    0.8245       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: 
 [[205  76]
 [ 64 457]]


In [ ]:
# LDA
classifier = LogisticRegression(random_state = 0)

classifier.fit(X_trainLDA, y_train)

#predicting results

y_pred = classifier.predict(X_testLDA)
print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: \n',confusion_matrix(y_test, y_pred))

Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: 
               precision    recall  f1-score   support

           0     0.5169    0.6548    0.5777       281
           1     0.7825    0.6699    0.7218       521

    accuracy                         0.6646       802
   macro avg     0.6497    0.6623    0.6498       802
weighted avg     0.6894    0.6646    0.6713       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: 
 [[184  97]
 [172 349]]


In [ ]:
# # Dùng WORD2VEC
# import re

# def cleanText(text):
#     cleaned = re.sub("[[\x5F]+|[a-z]|[0-9]"," ",text)
#     lowered = cleaned.lower()
#     return lowered.strip()

# cleanText("cái gì cơ ' ... ?>< á")

"á   ì  ơ ' ... ?>< á"

In [ ]:
x,y = np.asarray(df["text"]),np.asarray(df["label"])

label_map = {cat:index for index,cat in enumerate(np.unique(y))}
y_prep = np.asarray([label_map[l] for l in y])

y_prep

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
x_tokenized = [[w.lower() for w in sentence.split(" ") if (w != "" and w !='.' and w != '"' and w !=',')] for sentence in x]
x_tokenized[0]

['thiết',
 'kế',
 'đẹp',
 'nhưng',
 'không',
 'hiểu',
 'sao',
 'lại',
 'để',
 'đám',
 'chữ',
 '8.0',
 'autofocus',
 'ở',
 'camera',
 'chi',
 'không',
 'biết',
 'nhìn',
 'hơi',
 'quê',
 'nếu',
 'không',
 'có',
 'thì',
 'sẽ',
 'đẹp',
 'hơn',
 'giờ',
 'mấy',
 'máy',
 'cao',
 'cấp',
 'đâu',
 'ai',
 'để',
 'mấy',
 'thông',
 'số',
 'đó',
 'lên',
 'máy',
 'đâu']

In [ ]:
from gensim.models import Word2Vec
from collections import defaultdict

In [ ]:
import time

start = time.time()

model = Word2Vec(x_tokenized, window=6, min_count=5)

end = round(time.time()-start,2)
print("Thời gian chạy mất ",end,"giây.")

Thời gian chạy mất  0.95 giây.


In [ ]:
model.wv.most_similar("hả")

[('7', 0.9996337294578552),
 ('ăn', 0.9996076822280884),
 ('chip', 0.9996045231819153),
 ('tháng', 0.9996027946472168),
 ('sau', 0.9995883703231812),
 ('thêm', 0.9995842576026917),
 ('à', 0.9995743632316589),
 ('khó', 0.9995729923248291),
 ('hết', 0.9995708465576172),
 ('tầm', 0.9995705485343933)]

In [ ]:
class Sequencer():
    
    def __init__(self,
                 all_words,
                 max_words,
                 seq_len,
                 embedding_matrix
                ):
        
        self.seq_len = seq_len
        self.embed_matrix = embedding_matrix
        """
        temp_vocab = Vocab which has all the unique words
        self.vocab = Our last vocab which has only most used N words.
    
        """
        temp_vocab = list(set(all_words))
        self.vocab = []
        self.word_cnts = {}
        """
        Now we'll create a hash map (dict) which includes words and their occurencies
        """
        for word in temp_vocab:
            # 0 does not have a meaning, you can add the word to the list
            # or something different.
            count = len([0 for w in all_words if w == word])
            self.word_cnts[word] = count
            counts = list(self.word_cnts.values())
            indexes = list(range(len(counts)))
        
        # Now we'll sort counts and while sorting them also will sort indexes.
        # We'll use those indexes to find most used N word.
        cnt = 0
        while cnt + 1 != len(counts):
            cnt = 0
            for i in range(len(counts)-1):
                if counts[i] < counts[i+1]:
                    counts[i+1],counts[i] = counts[i],counts[i+1]
                    indexes[i],indexes[i+1] = indexes[i+1],indexes[i]
                else:
                    cnt += 1
        
        for ind in indexes[:max_words]:
            self.vocab.append(temp_vocab[ind])
                    
    def textToVector(self,text):
        # First we need to split the text into its tokens and learn the length
        # If length is shorter than the max len we'll add some spaces (100D vectors which has only zero values)
        # If it's longer than the max len we'll trim from the end.
        tokens = text.split()
        len_v = len(tokens)-1 if len(tokens) < self.seq_len else self.seq_len-1
        vec = []
        for tok in tokens[:len_v]:
            try:
                vec.append(self.embed_matrix[tok])
            except Exception as E:
                pass
        
        last_pieces = self.seq_len - len(vec)
        for i in range(last_pieces):
            vec.append(np.zeros(100,))
        
        return np.asarray(vec).flatten()

In [ ]:
sequencer = Sequencer(all_words = [token for seq in x_tokenized for token in seq],
              max_words = 1200,
              seq_len = 15,
              embedding_matrix = model.wv
             )

x_vecs = np.asarray([sequencer.textToVector(" ".join(seq)) for seq in x_tokenized])
print(x_vecs.shape)

(4009, 1500)


In [ ]:
# WORD2VEC 
from sklearn.decomposition import PCA
pca_model = PCA(n_components=50)
pca_model.fit(x_vecs)
print("Sum of variance ratios: ",sum(pca_model.explained_variance_ratio_))

Sum of variance ratios:  0.9973219193532243


In [ ]:
x_comps = pca_model.transform(x_vecs)
x_comps.shape

(4009, 50)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x_comps,y_prep,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(3207, 50)
(802, 50)
(3207,)
(802,)


In [ ]:
# Logistic
classifier = LogisticRegression(random_state = 0)

classifier.fit(x_train, y_train)

#predicting results

y_pred = classifier.predict(x_test)
print(classifier.score(x_test, y_test))
print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: \n',confusion_matrix(y_test, y_pred))

0.6758104738154613
Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp LogisticRegression: 
               precision    recall  f1-score   support

           0     0.3684    0.0275    0.0511       255
           1     0.6833    0.9781    0.8045       547

    accuracy                         0.6758       802
   macro avg     0.5258    0.5028    0.4278       802
weighted avg     0.5832    0.6758    0.5650       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp LogisticRegression: 
 [[  7 248]
 [ 12 535]]


In [ ]:
# SVM
classifier = svm.LinearSVC(random_state = 0)

classifier.fit(x_train, y_train)

#predicting results

y_pred = classifier.predict(x_test)
print("Score: ", classifier.score(x_test, y_test))
print('Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: \n',classification_report(y_test, y_pred, digits=4))
print('Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: \n',confusion_matrix(y_test, y_pred))

Score:  0.6745635910224439
Các độ đo Precision, Reacll, F1-Score đạt được từ mô hình phân lớp SVM: 
               precision    recall  f1-score   support

           0     0.3636    0.0314    0.0578       255
           1     0.6833    0.9744    0.8033       547

    accuracy                         0.6746       802
   macro avg     0.5235    0.5029    0.4305       802
weighted avg     0.5817    0.6746    0.5663       802

Ma trận nhầm lẫn đạt được từ mô hình phân lớp SVM: 
 [[  8 247]
 [ 14 533]]


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
